apiVersion: kustomize.config.k8s.io/v1beta1

namespace: kargo

resources: 
- kargo-ns.yaml
- kargo-secret-eso.yaml

helmCharts:
- name: kargo
  version: 1.2.1
  repo: oci://ghcr.io/akuity/kargo-charts
  releaseName: kargo
  namespace: kargo
  valuesFile: values.yaml
